name: Check Space Weather (Daily)

on:
  schedule:
    - cron: "0 0 * * *"  # every 24 hours at midnight UTC
  workflow_dispatch: # allows manual trigger

jobs:
  check-storm:
    runs-on: ubuntu-latest

    steps:
      - name: Call Netlify Function
        run: |
          curl -X GET "https://6a0e12926cd6eba9487bcbe5--magnetic-storms.netlify.app/.netlify/functions/checkstorms"
